package com.wide.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setParentId(String parentId) {
		set("parent_id", parentId);
	}

	public String getParentId() {
		return get("parent_id");
	}

	public void setParentIds(String parentIds) {
		set("parent_ids", parentIds);
	}

	public String getParentIds() {
		return get("parent_ids");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setSort(Double sort) {
		set("sort", sort);
	}

	public Double getSort() {
		return get("sort");
	}

	public void setHref(String href) {
		set("href", href);
	}

	public String getHref() {
		return get("href");
	}

	public void setTarget(String target) {
		set("target", target);
	}

	public String getTarget() {
		return get("target");
	}

	public void setIcon(String icon) {
		set("icon", icon);
	}

	public String getIcon() {
		return get("icon");
	}

	public void setIsShow(String isShow) {
		set("is_show", isShow);
	}

	public String getIsShow() {
		return get("is_show");
	}

	public void setPermission(String permission) {
		set("permission", permission);
	}

	public String getPermission() {
		return get("permission");
	}

	public void setCreateBy(String createBy) {
		set("create_by", createBy);
	}

	public String getCreateBy() {
		return get("create_by");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateBy(String updateBy) {
		set("update_by", updateBy);
	}

	public String getUpdateBy() {
		return get("update_by");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return get("remarks");
	}

	public void setDelFlag(String delFlag) {
		set("del_flag", delFlag);
	}

	public String getDelFlag() {
		return get("del_flag");
	}

}
